add `get_balances` param to enable_eth_with_tokens
KomodoPlatform/komodo-docs-mdx pull request #23
Opened 2023-05-05 09:08 UTC by smk762

Closes https://github.com/KomodoPlatform/komodo-docs-mdx/issues/20

Todo:
- [] update `enable_eth_with_tokens`
- [] update `enable_bch_with_tokens`
- [] update `enable_tendermint_with_assets`
- [] create `common_structures` and add `addressInfo`, `nodes` and `tokensRequest` objects

2023-05-05 19:47 UTC, shamardy requested changes
Thanks a lot for documenting this change!

2023-05-05 19:47 UTC, shamardy commented on src/pages/atomicdex/api/v20/enable_bch_with_tokens/index.mdx
> +| get_balances           | boolean          | Optional, defaults to `false`. If `true`, coin and token balances will be returned in the response (which takes a little longer to reply).
`get_balances` defaults to `true` to keep working as it was before if not set.

2023-05-05 19:47 UTC, shamardy commented on src/pages/atomicdex/api/v20/enable_bch_with_tokens/index.mdx
> +		"get_balances": true,
`"get_balances": true,` can be removed from the request since this is the default behaviour.

2023-05-08 15:10 UTC, shamardy approved these changes
Thank you for the fixes! LGTM!

2023-05-08 15:52 UTC, gcharang approved these changes

2023-05-08 15:52 UTC, merged